name: Build and deploy .NET application to container app dotnetcoresqldb-app-202512181411
on:
  push:
    branches:
    - main
permissions:
  id-token: write
  contents: read
env:
  CONTAINER_APP_CONTAINER_NAME: dotnetcoresqldb
  CONTAINER_APP_NAME: dotnetcoresqldb-app-202512181411
  CONTAINER_APP_RESOURCE_GROUP_NAME: msdocs-app-db-ef
  CONTAINER_REGISTRY_LOGIN_SERVER: dotnetcoresqldb20251218141409.azurecr.io
  DOTNET_CORE_VERSION: 8.0.x
  PROJECT_NAME_FOR_DOCKER: dotnetcoresqldb
  WORKING_DIRECTORY: .
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-quality: preview
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Log in to container registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.DotNetCoreSqlDb20251218141409_USERNAME_5783 }}
        password: ${{ secrets.DotNetCoreSqlDb20251218141409_PASSWORD_5783 }}
    - name: Build and push container image to registry
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" -c Release -r linux-x64 -p:PublishProfile=DefaultContainer -p:ContainerImageTag=${{ github.sha }} --no-self-contained -p:ContainerRegistry=${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} -bl
    - name: Upload binlog for investigation
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: binlog
        path: msbuild.binlog

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    # IMPORTANT: You must checkout the code in every job that needs access to your files
    - name: Checkout to the branch
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to containerapp
      uses: azure/CLI@v2
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.DotNetCoreSqlDb20251218141409_USERNAME_5783 }} --password ${{ secrets.DotNetCoreSqlDb20251218141409_PASSWORD_5783 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}

    - name: Run EF
      shell: bash
      env:
        # These help the 'Active Directory Default' auth find your login
        AZURE_CLIENT_ID: ${{ vars.dotnetcoresqldb_app_202512181411_CLIENT_ID_5783 }}
        AZURE_TENANT_ID: ${{ vars.dotnetcoresqldb_app_202512181411_TENANT_ID_5783 }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      run: |
        dotnet tool install --global dotnet-ef || echo "Already installed"
        PROJ_PATH=$(find . -name "*.csproj" -print -quit)
        
        dotnet ef database update \
          --project "$PROJ_PATH" \
          --connection "${{ secrets.DBConnection }}"