name: Build and deploy .NET application to container app dotnetcoresqldb-app-202512181411
on:
  push:
    branches:
    - main
permissions:
  id-token: write
  contents: read
env:
  CONTAINER_APP_CONTAINER_NAME: dotnetcoresqldb
  CONTAINER_APP_NAME: dotnetcoresqldb-app-202512181411
  CONTAINER_APP_RESOURCE_GROUP_NAME: msdocs-app-db-ef
  CONTAINER_REGISTRY_LOGIN_SERVER: dotnetcoresqldb20251218141409.azurecr.io
  DOTNET_CORE_VERSION: 8.0.x
  PROJECT_NAME_FOR_DOCKER: dotnetcoresqldb
  WORKING_DIRECTORY: .
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-quality: preview
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Log in to container registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.DotNetCoreSqlDb20251218141409_USERNAME_5783 }}
        password: ${{ secrets.DotNetCoreSqlDb20251218141409_PASSWORD_5783 }}
    - name: Build and push container image to registry
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" -c Release -r linux-x64 -p:PublishProfile=DefaultContainer -p:ContainerImageTag=${{ github.sha }} --no-self-contained -p:ContainerRegistry=${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} -bl
    - name: Upload binlog for investigation
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: binlog
        path: msbuild.binlog
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    # - name: Azure Login
    #   uses: azure/login@v2
    #   with:
    #     client-id: ${{ vars.dotnetcoresqldb_app_202512181411_CLIENT_ID_5783 }}
    #     tenant-id: ${{ vars.dotnetcoresqldb_app_202512181411_TENANT_ID_5783 }}
    #     subscription-id: ${{ vars.dotnetcoresqldb_app_202512181411_SUBSCRIPTION_ID_5783 }}
    #     allow-no-subscriptions: true
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ vars.dotnetcoresqldb_app_202512181411_CLIENT_ID_5783 }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ vars.dotnetcoresqldb_app_202512181411_SUBSCRIPTION_ID_5783 }}","tenantId":"${{ vars.dotnetcoresqldb_app_202512181411_TENANT_ID_5783 }}"}'
    - name: Deploy to containerapp
      uses: azure/CLI@v2
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.DotNetCoreSqlDb20251218141409_USERNAME_5783 }} --password ${{ secrets.DotNetCoreSqlDb20251218141409_PASSWORD_2DA0 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
    - name: Run EF 
      run: | 
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef database update -p DotNetCoreSqlDb --connection '${{ secrets.DBConnection }}'
